FROM ubuntu:latest
MAINTAINER Vladimir "vladimiriacobm@gmail.com"

RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential
COPY requirements.txt data_getter.py /app/
WORKDIR /app
RUN pip install -r requirements.txt
